#spring:
#  datasource:
#      driver-class-name: com.mysql.jdbc.Driver
#      username: root
#      password: 123456
#      url: jdbc:mysql://192.168.0.106/sell?characterEncoding=utf-8&useSSL=false
#    jpa:
#      show-sql: true
#  sever:
#    context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: /var/log/tomcat
#  file: /var/log/tomcat
#  level: debug